time_steps: 50
step: 50
features: 3
dimension1: 64
dropout: 0.5
dimension2: 14
num_classes: 16
epochs: 15
num_iteration: 10
train_ids: [1, 2, 3, 4, 5, 6, 7, 8]
gestures_source : ['right', 'left', 'square_C', 'square_AC', 'upRight', 'upLeft', 'rightDown', 'leftDown',
                  'v', 'v_Mirror', 'v_Reverse', 'v_ReverseM', 's_Top', 's_TopM', 's_Down', 's_DownM']
gestures_target: ['circle', 'double tap', 'rotate_f_s', 'rotate_s_f', 'shake', 'tap']
